version: '3'
services:
  public-db:
    image: mariadb
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: conquers666
      MYSQL_USER: conquers666
      MYSQL_PASSWORD: conquers666
      MYSQL_DATABASE: hfmu
    ports:
      - "3340:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d  # 挂载自定义配置目录，即上述的 mysql/conf/django-blog.cnf 中的配置
      - ./mysql/data:/var/lib/mysql  # 挂载数据目录
      - ./mysql/log:/var/log  # 挂载日志目录
  public-ec-web:
    container_name: public-ec-django-web
    sysctls:
      net.core.somaxconn: 32768
    build:
      context: .
      dockerfile: Dockerfile_pd
    restart: always
    command: >
      bash -c "uwsgi  --emperor uwsgi.ini"
    ports:
      - "2002:2000"
    depends_on:
      - public-db
      - public-redis
    volumes:
      - ./web:/app
      - ./log:/root/var/log
      - rest_framework:/usr/local/lib/python3.7/site-packages/rest_framework/static/rest_framework
  public-redis:
    image: redis:alpine
    restart: always
    ports:
      - 6444:6379
    volumes:
      - ./data/redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    container_name: nginx-ezgo-django-web
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    restart: always
    ports:
      - "2000:80"
    volumes:
      - ./web:/app
      - ./log:/var/log/nginx
      - rest_framework:/usr/share/nginx/html/static/rest_framework
    depends_on:
      - public-ec-web
volumes:
  rest_framework: