import string
import random

letters = string.ascii_letters + string.digits + '_'
cn_name = [
    '游盈以',
    '謝佑樺',
    '邱建娥',
    '王惠嘉',
    '李承延',
    '黃子妃',
    '張家君',
    '陳姿蓉',
    '黃旺惠',
    '黃佳燕',
    '李振娥',
    '黃雯婷',
    '彭韻如',
    '黃士帆',
    '鄭佳玲',
    '崔智傑',
    '謝淑華',
    '羅華凱',
    '陳胤禎',
    '林一禾',
    '郭俊法',
    '蘇平銘',
    '林介春',
    '林慧玲',
    '紀辰聿',
    '李孟隆',
    '陳雅玲',
    '蔡文華',
    '羅庭邦',
    '劉珮啟',
    '陳禹芷',
    '王璇劭',
    '洪嘉義',
    '張雅其',
    '蘇怡君',
    '蔡明皓',
    '王建諭',
    '林威雪',
    '方世典',
    '羅昕寧',
    '何浩學',
    '姜雅琳',
    '林怡珊',
    '黃佩君',
    '王萬嬌',
    '黃順易',
    '劉蕙如',
    '李孟男',
    '劉文佩',
    '余怡菁',
    '張進琬',
    '陳宏俊',
    '李書蓁',
    '袁軒航',
    '孫若陽',
    '陳威齊',
    '黃郁年',
    '謝淑敏',
    '吳翠邦',
    '陳峻源',
    '明婷云',
    '陳林軒',
    '趙添意',
    '黃韻如',
    '王碧虹',
    '蔡桂丹',
    '鄒宗儒',
    '李仕筠',
    '姚怡樺',
    '許哲宜',
    '張家士',
    '許惠虹',
    '劉建宏',
    '陳雅竹',
    '黃淑福',
    '李峻善',
    '簡怡萍',
    '何美惠',
    '謝慧婷',
    '林國啟',
    '宋豪瑄',
    '何怡伶',
    '黃如緯',
    '陳怡潔',
    '王富添',
    '李文凱',
    '陳怡沛',
    '潘必宜',
    '李凱翔',
    '陳思齊',
    '陳婉瑜',
    '陳惠玲',
    '陳雅一',
    '王雅萍',
    '王明名',
]
en_name = [
    'Kay Davis Barker',
    'Tyler Hudson',
    'Katrina Butler Lawrence',
    'Hector Arnold',
    'Lisa E. Harper',
    'Violet Joan Parker',
    'Stacy Wanda Higgins',
    'Violet Fleming Holmes',
    'Dawn D. Aguilar',
    'Gina Chapman Porter',
    'Leah E. Miles',
    'Jenny Ana Carter',
    'Sarah Phillips Howard',
    'Jonathan Maldonado Parks',
    'Marvin Rodgers',
    'Martin Bowman',
    'Clifford Darryl Frazier',
    'Francisco Marshall Perry',
    'Alicia W. Hansen',
    'Bradley Gomez',
    'Theodore K. Coleman',
    'Travis F. Woods',
    'Jose T. Erickson',
    'Phillip P. Myers',
    'Juanita Gardner Hicks',
    'Renee Hammond',
    'Kurt M. Miles',
    'June S. Reid',
    'Heidi Morris Farmer',
    'Louise Parker',
]
banner_args = [
    dict(
        display_type=False,
        start_time='2019-05-20',
        end_time='2022-06-20',
    ),
    dict(
        display_type=False,
        start_time='2019-05-20',
        end_time='2022-06-20',
    ),
    dict(
        display_type=False,
        start_time='2019-05-20',
        end_time='2022-06-20',
    ),
    dict(
        display_type=True,
        start_time=None,
        end_time=None,
    ),
    dict(
        display_type=True,
        start_time=None,
        end_time=None,
    ),
    dict(
        display_type=True,
        start_time=None,
        end_time=None,
    ),
    dict(
        display_type=False,
        start_time='2019-06-20',
        end_time='2019-09-20',
    ),
    dict(
        display_type=False,
        start_time='2019-06-20',
        end_time='2019-09-20',
    ),

]

categories = [
    {
        'name': '功效分類',
        'children': [
            {'name': '增加肌肉', 'image_url': 'efficacy/a-01.svg'},
            {'name': '幫助睡眠', 'image_url': 'efficacy/a-02.svg'},
            {'name': '止痛止癢退燒', 'image_url': 'efficacy/a-03.svg'},
            {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
            {'name': '生髮護髮', 'image_url': 'efficacy/a-05.svg'},
            {'name': '神經系統功能', 'image_url': 'efficacy/a-06.svg'},
            {'name': '綜合維他命', 'image_url': 'efficacy/a-07.svg'},
            {'name': '維護關節', 'image_url': 'efficacy/a-08.svg'},
            {'name': '肝臟保健', 'image_url': 'efficacy/a-09.svg'},
            {'name': '肺部保健', 'image_url': 'efficacy/a-10.svg'},
            {'name': '血糖與膽固醇控制', 'image_url': 'efficacy/a-11.svg'},
            {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
            {'name': '護膚護甲', 'image_url': 'efficacy/a-13.svg'},
            {'name': '骨骼保健', 'image_url': 'efficacy/a-14.svg'},
            {'name': '抗氧化', 'image_url': 'efficacy/a-15.svg'},
            {'name': '心血管與心臟保健', 'image_url': 'efficacy/a-16.svg'},
            {'name': '補腦補憶', 'image_url': 'efficacy/a-17.svg'},
            {'name': '眼睛保健', 'image_url': 'efficacy/a-18.svg'},
            {'name': '胃與腸道保健', 'image_url': 'efficacy/a-19.svg'},
            {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
            {'name': '泌尿道保健', 'image_url': 'efficacy/a-21.svg'},
            {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
            {'name': '兩性健康', 'image_url': 'efficacy/a-23.svg'},
            {'name': '減肥瘦身', 'image_url': 'efficacy/a-24.svg'},
            {'name': '孕婦與寶寶', 'image_url': 'efficacy/a-25.svg'},
        ]
    },
    {
        'name': '成分分類',
        'children': [
            {'name': '其他成分', 'image_url': 'main_contain/b-01.svg',
             'children': [
                 {'name': '人蔘', 'image_url': 'efficacy/a-01.svg'},
                 {'name': '山楂果', 'image_url': 'efficacy/a-02.svg'},
                 {'name': '消化酵素', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '石柳', 'image_url': 'efficacy/a-05.svg'},
             ]},
            {'name': '大豆異黃酮', 'image_url': 'main_contain/b-02.svg'},
            {'name': '益生菌 / 乳酸菌', 'image_url': 'main_contain/b-03.svg'},
            {'name': '綜合維他命', 'image_url': 'main_contain/b-04.svg'},
            {'name': '維生素B群', 'image_url': 'main_contain/b-05.svg'},
            {'name': '脂肪酸 / 魚油', 'image_url': 'main_contain/b-06.svg'},
            {'name': '葉酸', 'image_url': 'main_contain/b-07.svg'},
            {'name': '葡萄糖胺', 'image_url': 'main_contain/b-08.svg'},
            {'name': '銀杏', 'image_url': 'main_contain/b-09.svg'},
            {'name': '葡萄籽', 'image_url': 'main_contain/b-10.svg'},
            {'name': '奶薊草', 'image_url': 'main_contain/b-11.svg'},
            {'name': '葉黃素', 'image_url': 'main_contain/b-12.svg'},
            {'name': '鈣片', 'image_url': 'main_contain/b-13.svg'},
            {'name': '鋸棕櫚', 'image_url': 'main_contain/b-14.svg'},
            {'name': 'Minoxidil / 米諾地爾', 'image_url': 'main_contain/b-15.svg'},
        ]
    },
    {
        'name': '使用者分類',
        'children': [
            {'name': '女用營養系列', 'image_url': 'user_classification/c-01.svg',
             'children': [
                 {'name': '增加肌肉', 'image_url': 'efficacy/a-01.svg'},
                 {'name': '幫助睡眠', 'image_url': 'efficacy/a-02.svg'},
                 {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '生髮護髮', 'image_url': 'efficacy/a-05.svg'},
                 {'name': '神經系統功能', 'image_url': 'efficacy/a-06.svg'},
                 {'name': '綜合維他命', 'image_url': 'efficacy/a-07.svg'},
                 {'name': '維護關節', 'image_url': 'efficacy/a-08.svg'},
                 {'name': '肝臟保健', 'image_url': 'efficacy/a-09.svg'},
                 {'name': '肺部保健', 'image_url': 'efficacy/a-10.svg'},
                 {'name': '血糖與膽固醇控制', 'image_url': 'efficacy/a-11.svg'},
                 {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
                 {'name': '抗氧化', 'image_url': 'efficacy/a-15.svg'},
                 {'name': '心血管與心臟保健', 'image_url': 'efficacy/a-16.svg'},
                 {'name': '補腦補憶', 'image_url': 'efficacy/a-17.svg'},
                 {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
                 {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
                 {'name': '兩性健康', 'image_url': 'efficacy/a-23.svg'},
                 {'name': '減肥瘦身', 'image_url': 'efficacy/a-24.svg'},
             ]
             },
            {'name': '男用營養系列', 'image_url': 'user_classification/c-02.svg',
             'children': [
                 {'name': '幫助睡眠', 'image_url': 'efficacy/a-02.svg'},
                 {'name': '止痛止癢退燒', 'image_url': 'efficacy/a-03.svg'},
                 {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '生髮護髮', 'image_url': 'efficacy/a-05.svg'},
                 {'name': '神經系統功能', 'image_url': 'efficacy/a-06.svg'},
                 {'name': '綜合維他命', 'image_url': 'efficacy/a-07.svg'},
                 {'name': '維護關節', 'image_url': 'efficacy/a-08.svg'},
                 {'name': '肝臟保健', 'image_url': 'efficacy/a-09.svg'},
                 {'name': '肺部保健', 'image_url': 'efficacy/a-10.svg'},
                 {'name': '血糖與膽固醇控制', 'image_url': 'efficacy/a-11.svg'},
                 {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
                 {'name': '護膚護甲', 'image_url': 'efficacy/a-13.svg'},
                 {'name': '骨骼保健', 'image_url': 'efficacy/a-14.svg'},
                 {'name': '抗氧化', 'image_url': 'efficacy/a-15.svg'},
                 {'name': '心血管與心臟保健', 'image_url': 'efficacy/a-16.svg'},
                 {'name': '眼睛保健', 'image_url': 'efficacy/a-18.svg'},
                 {'name': '胃與腸道保健', 'image_url': 'efficacy/a-19.svg'},
                 {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
                 {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
                 {'name': '兩性健康', 'image_url': 'efficacy/a-23.svg'},
             ]},
            {'name': '50歲以上女用營養系列 / 乳酸菌', 'image_url': 'user_classification/c-03.svg',
             'children': [
                 {'name': '幫助睡眠', 'image_url': 'efficacy/a-02.svg'},
                 {'name': '止痛止癢退燒', 'image_url': 'efficacy/a-03.svg'},
                 {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '生髮護髮', 'image_url': 'efficacy/a-05.svg'},
                 {'name': '神經系統功能', 'image_url': 'efficacy/a-06.svg'},
                 {'name': '綜合維他命', 'image_url': 'efficacy/a-07.svg'},
                 {'name': '維護關節', 'image_url': 'efficacy/a-08.svg'},
                 {'name': '肝臟保健', 'image_url': 'efficacy/a-09.svg'},
                 {'name': '肺部保健', 'image_url': 'efficacy/a-10.svg'},
                 {'name': '血糖與膽固醇控制', 'image_url': 'efficacy/a-11.svg'},
                 {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
                 {'name': '護膚護甲', 'image_url': 'efficacy/a-13.svg'},
                 {'name': '骨骼保健', 'image_url': 'efficacy/a-14.svg'},
                 {'name': '抗氧化', 'image_url': 'efficacy/a-15.svg'},
                 {'name': '心血管與心臟保健', 'image_url': 'efficacy/a-16.svg'},
                 {'name': '補腦補憶', 'image_url': 'efficacy/a-17.svg'},
                 {'name': '眼睛保健', 'image_url': 'efficacy/a-18.svg'},
                 {'name': '胃與腸道保健', 'image_url': 'efficacy/a-19.svg'},
                 {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
                 {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
                 # todo check image
                 {'name': '孕婦與寶寶', 'image_url': 'efficacy/a-22.svg'},
             ]},
            {'name': '50歲以上男用營養系列', 'image_url': 'user_classification/c-04.svg',
             'children': [
                 {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '生髮護髮', 'image_url': 'efficacy/a-05.svg'},
                 {'name': '維護關節', 'image_url': 'efficacy/a-08.svg'},
                 {'name': '血糖與膽固醇控制', 'image_url': 'efficacy/a-11.svg'},
                 {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
                 {'name': '護膚護甲', 'image_url': 'efficacy/a-13.svg'},
                 {'name': '骨骼保健', 'image_url': 'efficacy/a-14.svg'},
                 {'name': '抗氧化', 'image_url': 'efficacy/a-15.svg'},
                 {'name': '心血管與心臟保健', 'image_url': 'efficacy/a-16.svg'},
                 {'name': '補腦補憶', 'image_url': 'efficacy/a-17.svg'},
                 {'name': '眼睛保健', 'image_url': 'efficacy/a-18.svg'},
                 {'name': '胃與腸道保健', 'image_url': 'efficacy/a-19.svg'},
                 {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
                 {'name': '泌尿道保健', 'image_url': 'efficacy/a-21.svg'},
                 {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
             ]},
            {'name': '兒童與青少年', 'image_url': 'user_classification/c-05.svg',
             'children': [
                 {'name': '幫助睡眠', 'image_url': 'efficacy/a-02.svg'},
                 {'name': '止痛止癢退燒', 'image_url': 'efficacy/a-03.svg'},
                 {'name': '增壓抗壓與抗憂鬱', 'image_url': 'efficacy/a-04.svg'},
                 {'name': '肝臟保健', 'image_url': 'efficacy/a-09.svg'},
                 {'name': '補血活血', 'image_url': 'efficacy/a-12.svg'},
                 {'name': '增強免疫力', 'image_url': 'efficacy/a-20.svg'},
                 {'name': '泌尿道保健', 'image_url': 'efficacy/a-21.svg'},
                 {'name': '活力營養', 'image_url': 'efficacy/a-22.svg'},
                 {'name': '兩性健康', 'image_url': 'efficacy/a-23.svg'},
                 # todo fake
                 {'name': '孕婦與寶寶', 'image_url': 'efficacy/a-22.svg'},
             ]},
        ]
    }

]

brands = [
    'A La Maison de Provence',
    'A Vogel',
    'A.C. Grace Company',
    'A+D',
    'Abkit',
    'Abra Therapeutics',
    'Absolute Nutrition',
    'AbsorbAid',
    'AccuRelief',
    'Actipet',
    'Acure',
    'Babo Botanicals',
    'Baby Banana',
    'BabyGanics',
    'Bach',
    'Back to Nature',
    'Badger Company',
    'Balance Bar',
    'Balanceuticals',
    'Band Aid',
    'Banila Co.',
    'Banza',
    'Bar Keepers Friend',
    'Barbaras Bakery',
    'Bare Republic',
    'Bare Snacks',
    'C.C. Pollen',
    'Cafe Altura',
    'Cafix',
    'Cailyn',
    'Caleb Treeze Organic Farm',
    'California Gold Nutrition',
    'California Mango',
    'California Natural',
    'California Olive Ranch',
    'Daelmans',
    'Dagoba Organic Chocolate',
    'Daily Concepts',
    'Daily Wellness Company',
    'Dandy Blend',
    'Dang',
    'Dapple',
    'Darford',
    'Dastony',
    'Earnest Eats',
    'Earth Balance',
    'Earth Circle Organics',
    'Earth Mama',
    'Earth Rated',
    'Earth Science',
    'Earth Therapeutics',
    'Earthrise',
    'Face Doctor',
    'Fairhaven Health',
    'Fairy Tales',
    'Familia',
    'Fantasia',
    'Fatco',
    'Fearn Natural Food',
    'G.H. Cretors',
    'Gaea',
    'Gaia Herbs',
    'Gaia Herbs Professional Solutions',
    'Garden Greens',
    'Garden of Life',
    'Gaspari Nutrition',
    'Hair Off',
    'Hakubaku',
    'Halo',
    'Hampstead Tea',
    'Hana Beverages',
    'Happy Family Organi',
    'I Heart Keenwah',
    'i play Inc.',
    'If You Care',
    '16 Brand',
    '1Kvit-C',
    '21st Century',
    '23 Years Old',
    '4th & Heart',
]


def get_random_letters(count):
    return ''.join(random.choices(letters, k=count))


def get_random_number(count):
    return ''.join(random.choices(string.digits, k=count))
